<?php

/**
 * PluginsfJQueryExtraFormFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfJQueryExtraFormFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfJQueryExtraFormFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfJQueryExtraFormFile');
    }
}